# Generated by Django 3.0.5 on 2025-01-26 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20250126_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='question',
            name='start_time',
        ),
    ]
