# Generated by Django 3.0.5 on 2025-04-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20250429_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='given_time',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
