# Generated by Django 3.0.5 on 2025-05-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_alter_course_id_alter_question_id_alter_result_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['course', 'question_type'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AddField(
            model_name='question',
            name='blank_answer',
            field=models.CharField(blank=True, help_text='Correct answer for explanation questions', max_length=200, null=True, verbose_name='Blank Answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='case_sensitive',
            field=models.BooleanField(default=False, help_text='Should the answer be case sensitive?', verbose_name='Case Sensitive'),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation for the correct answer', null=True, verbose_name='Explanation'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('FIB', 'Fill in the Blank')], default='MCQ', max_length=3, verbose_name='Question Type'),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Correct Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Option 1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Option 2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Option 3'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Option 4'),
        ),
        migrations.AlterField(
            model_name='result',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
