# Generated by Django 3.0.5 on 2025-06-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_auto_20250601_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
