# Generated by Django 3.0.5 on 2025-05-14 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_auto_20250513_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='question',
            name='related_question',
        ),
    ]
