# Generated by Django 3.0.5 on 2025-01-26 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20250126_1351'),
        ('student', '0003_examattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='course',
            field=models.ForeignKey(default='100', on_delete=django.db.models.deletion.CASCADE, to='exam.Course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='examattempt',
            unique_together={('student', 'course')},
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='exam',
        ),
    ]
