# Generated by Django 3.0.5 on 2025-01-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20250126_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='attempted',
            field=models.BooleanField(default=False),
        ),
    ]
