# Generated by Django 3.0.5 on 2025-02-19 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_examattempt_attempted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile_pic',
        ),
    ]
