# Generated by Django 3.0.5 on 2025-04-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='organization',
            field=models.CharField(default='pice', max_length=200),
            preserve_default=False,
        ),
    ]
