# Generated by Django 3.2.6 on 2025-04-29 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20250429_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='current_exam',
        ),
        migrations.RemoveField(
            model_name='student',
            name='exam_start_time',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_taking_exam',
        ),
        migrations.DeleteModel(
            name='ExamSession',
        ),
    ]
