# Generated by Django 3.2.6 on 2025-04-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20250429_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
